name: notification-service

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    uses: ./.github/workflows/run-script.yml@master
    with:
      script: build

  lint:
    uses: ./.github/workflows/run-script.yml@master
    with:
      script: lint

  test:
    uses: ./.github/workflows/run-script.yml@master
    with:
      script: test