name: Build

on:
  push:
    branches:
      - develop
      - master
      - 'feature/**'
      - 'release/**'
      - 'bugfix/**'
      - 'dependabot/**'

jobs:
  build:
    name: Run ${{ inputs.script }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  lint:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: lint

  test:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: test

  test-e2e:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: test:e2e
