name: Build

on:
  push:
    branches:
      - develop
      - master
      - 'feature/**'
      - 'release/**'
      - 'bugfix/**'
      - 'dependabot/**'

jobs:
  build:
    name: Run ${{ inputs.script }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
        with:
          script: build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  lint:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: lint

  test:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: test

  test-e2e:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: test:e2e
