name: notification-service

on:
  push:
    branches:
      - *

jobs:
  build:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: build

  lint:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: lint

  test:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: test