name: Test

on:
  push:
    branches:
      - develop
      - master
      - 'feature/**'
      - 'release/**'
      - 'bugfix/**'
      - 'dependabot/**'

jobs:
  build:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: build

  lint:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: lint

  test:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: test

  test-e2e:
    uses: tim-hoffmann/notification-service/.github/workflows/run-script.yml@master
    with:
      script: test:e2e
